import sys,os,pwd,shutil,subprocess,tarfile
from javaset import javasetup 
from variables import*

x = variab()


def install(input_cases):
    os.environ["http_proxy"] = "http://www-proxy.us.oracle.com:80"
    os.environ["https_proxy"] = "http://www-proxy.us.oracle.com:80"
    print ("Starting installer")		  
    if (input_cases==1):
	    javasetup();
            os.chdir(x.instPath)
	    print("Downloading Weblogic 12213 FMW installer")
	    print("currently at " + x.instPath)
	    subprocess.call(["wget",x.fmw_disk_url])
    	    print("Downloading ODI installer ")
	    subprocess.call(["wget", x.odi_122126])
	    print("installer download completed successfully ! \n")
	    tar = tarfile.open(x.fmw_disk_url.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"fmw12213")
            subprocess.call(["wget",x.fmw_12213_rsp])
	    subprocess.call(["unzip", "*.zip"])
	    print("installing FMW weblogic infra \n")
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_infrastructure.jar", "-silent", "-responseFile" ,x.instPath+"fmw12213/fmw.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("installing ODI over WLS ................................\n ")
	    os.chdir(x.instPath)
	    tar = tarfile.open(x.odi_122126.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"odi_122126")
	    subprocess.call(["unzip", "*.zip"])
            subprocess.call(["wget",x.standalone_odi_rsp_122126])
            subprocess.call(["java", "-jar", "fmw_12.2.1.2.6_odi.jar", "-silent", "-responseFile" ,x.instPath+"odi_122126/standalone.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("ODI installation successfuly please note  x.fmw_path=\scratch\u01\app\oracle\product\ fmw_12213")
	    print("ODI path =\scratch\u01\app\oracle\product\ fmw_12213\odi_122126standalone")
    elif(input_cases==2):
	    javasetup();
	    os.chdir(x.instPath)
	    print("Downloading Weblogic 12213 FMW installer")
	    print("currently at " + x.instPath)
 	    subprocess.call(["wget",x.fmw_disk_url])
	    print("Downloading ODI installer ")
            subprocess.call(["wget",x.odi_122126])
	    print("installer download completed successfully ! \n")
	    tar = tarfile.open(x.fmw_disk_url.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"fmw12213")
            print("downloading fmw RSP")
            subprocess.call(["wget",x.fmw_12213_rsp])
            subprocess.call(["unzip", "*.zip"])
	    print("installing FMW weblogic infra \n")
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_infrastructure.jar", "-silent", "-responseFile" ,x.instPath+"fmw12213/fmw.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("installing ODI over WLS ................................\n ")
	    os.chdir(x.instPath)
	    tar = tarfile.open(x.odi_122126.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"odi_122126")
	    subprocess.call(["unzip", "*.zip"])
            print("downloading ODI 12.2.1.2.6 enterprise Response file  ")
            subprocess.call(["wget",x.enterprise_odi_rsp_122126])
	    subprocess.call(["java", "-jar", "fmw_12.2.1.2.6_odi.jar", "-silent", "-responseFile" ,x.instPath+"odi_122126/enterprise.rsp", "-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("ODI installation successfuly please note x.fmw_path=\scratch\u01\app\oracle\product\ fmw_12213")
	    print("ODI path =\scratch\u01\app\oracle\product\ fmw_12213\odi_122126enterprise")
    elif(input_cases==3):
	    javasetup();
	    os.chdir(x.instPath)
	    print("Downloading Weblogic 12213 FMW installer")
	    print("currently at " + x.instPath)
 	    subprocess.call(["wget",fmw_disk_url])
	    print("Downloading ODI installer ")
            subprocess.call(["wget", odi_12213])
	    print("installer download completed successfully ! \n")
	    tar = tarfile.open(x.fmw_disk_url.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"fmw12213")
	    subprocess.call(["unzip", "*.zip"])
            print("downloading fmw 12213 response file")
            subprocess.call(["wget",x.fmw_12213_rsp])
	    print("installing FMW weblogic infra \n")
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_infrastructure.jar", "-silent", "-responseFile" ,x.instPath+"fmw12213/fmw.rsp", "-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("installing ODI over WLS ................................\n ")
	    os.chdir(x.instPath)
	    tar = tarfile.open(x.odi_12213.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"odi12213")
            print ("downloading odi 12213 odi  standard response file")
            subprocess.call(["wget",x.standalone_odi_rsp_12213])
	    subprocess.call(["unzip", "*.zip"])
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_odi.jar", "-silent", "-responseFile" ,x.instPath+"odi12213/odi_12213_standalone.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("ODI installation successfuly completed please note x.fmw_path=\scratch\u01\app\oracle\product\ fmw_12213")
	    print("ODI path =\scratch\u01\app\oracle\product\ fmw_12213\odi_12213standalone")
    elif(input_cases==4):
	    javasetup();
	    os.chdir(x.instPath)
	    print("Downloading Weblogic 12213 FMW installer")
	    print("currently at " + x.instPath)
 	    subprocess.call(["wget",x.fmw_disk_url])
	    print("Downloading ODI installer ")
            subprocess.call(["wget",x.odi12213])
	    print("installer download completed successfully ! \n")
	    tar = tarfile.open(x.fmw_disk_url.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"fmw12213")
            print("downloading fmw 12213 response file")
            subprocess.call(["wget",x.fmw_12213_rsp])
	    subprocess.call(["unzip", "*.zip"])
	    print("installing FMW weblogic infra \n")
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_infrastructure.jar", "-silent", "-responseFile" ,x.instPath+"fmw12213/fmw.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("installing ODI over WLS ................................\n ")
	    os.chdir(x.instPath)
	    tar = tarfile.open(x.odi_12213.split('/')[-1])
	    tar.extractall()
	    tar.close()
	    os.chdir(x.instPath+"odi12213")
	    subprocess.call(["unzip", "*.zip"])
            print ("downloading odi 12213 odi response file")
            subprocess.call(["wget",x.enterprise_odi_rsp_12213])
	    subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_odi.jar", "-silent", "-responseFile" ,x.instPath+"odi12213/odi_12213_enterprise.rsp","-invPtrLoc","/scratch/u01/app/oraInventory/oraInst.loc"])
	    print("ODI installation successfuly completed ! please note  x.fmw_path=\scratch\u01\app\oracle\product\ fmw_12213")
	    print("ODI path =\scratch\u01\app\oracle\product\ fmw_12213\odi12213enterprise")
    elif(input_cases==5):
    	javasetup();
	print("Downloading FMW installer")
	os.chdir(x.instPath)
    	print("currently at " + x.instPath)
    	subprocess.call(["wget",x.fmw_disk_url])
    	tar = tarfile.open(x.fmw_disk_url.split('/')[-1])
    	tar.extractall()
    	tar.close()
    	os.chdir(x.instPath+"fmw12213")
        print("downloading fmw 12213 response file")
        subprocess.call(["wget",x.fmw_12213_rsp])
    	subprocess.call(["unzip", "*.zip" ])
    	subprocess.call(["java", "-jar", "fmw_12.2.1.3.0_infrastructure.jar", "-silent", "-responseFile" ,x.instPath+"fmw12213/fmw.rsp"])
    	print("FMW installation successfuly comepleted !  please note --->  fmw_path=\scratch\u01\app\oracle\product\ fmw12213")
    else:
       print("Wrong input exiting the installer")
       sys.exit()
    print ("\n Installing files Complete.\n")
    print ("\n Script Completed Successfully... \n")

