class variab:

    basePath = "/scratch/u01"
    instPath = "/scratch/stage/"
    db_user = "sys"
    oraclePath = basePath + "/app/oracle/product/"
    java_path = oraclePath + "JAVA"
    fmw_path = oraclePath+"fmw12213"
    install_user = "gbuora"
    invPath = basePath + "/app/oraInventory"
    java_url = "http://Dummy_URL_XYZ"
    odi_122126="http://Dummy_URL_XYZ"
    odi_12213="http://Dummy_URL_XYZ"
    fmw_disk_url="http://Dummy_URL_XYZ"
    wls_12203="http://Dummy_URL_XYZ"
    standalone_odi_rsp_122126="http://Dummy_URL_XYZ"
    enterprise_odi_rsp_122126="http://Dummy_URL_XYZ"
    standalone_odi_rsp_12213="http://Dummy_URL_XYZ"
    enterprise_odi_rsp_12213= "http://Dummy_URL_XYZ"
    fmw_12213_rsp= "http://Dummy_URL_XYZ"
